# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.

version: 2
updates:
# Enable version updates for GitHub actions
- package-ecosystem: "github-actions"
  directory: "/"
  commit-message:
    prefix: "[GitHub Action] "
  schedule:
    interval: "daily"
    time: "02:00"
    timezone: "Europe/Prague"
  groups:
    major-updates:
      patterns:
        - "*"
      update-types:
        - "major"
    support-dependencies:
      applies-to: version-updates
      patterns:
        - "*"
      update-types:
        - "minor"
        - "patch"
    security-dependencies:
      applies-to: security-updates
      patterns:
        - "*"
      update-types:
        - "minor"
        - "patch"
  labels:
    - "dependencies"
    - "github-actions"
