name: Scorecard supply-chain security

on:
  branch_protection_rule:
  schedule:
    - cron: '35 23 * * 5'
  push:
    branches:
      - 'main'
      - 'stable'
    paths-ignore:
      - '.github/workflows/*'

permissions:
  contents: read

jobs:
  scorecard:
    permissions:
      actions: read
      contents: read
      security-events: write
      id-token: write
    uses: dafneb/.github/.github/workflows/scorecard.yml@3f124afb6b96358a69a6a8e70a1b62904b4da4cb
    secrets:
      SCORECARD_TOKEN: ${{ secrets.SCORECARD_TOKEN }}
